# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    unused_import: ignore
    dead_code: ignore
    library_private_types_in_public_api: ignore
    unused_local_variable: ignore
    prefer_const_constructors: ignore
    sized_box_for_whitespace: ignore
    unnecessary_brace_in_string_interps: ignore
    await_only_futures: ignore
    avoid_print: ignore
    prefer_const_declarations: ignore
    use_key_in_widget_constructors: ignore
    prefer_final_fields: ignore
    prefer_const_literals_to_create_immutables: ignore
    use_build_context_synchronously: ignore
    unnecessary_const: ignore
    use_super_parameters: ignore
    unused_field: ignore
linter:

  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at https://dart.dev/lints.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    avoid_print: true  # Uncomment to disable the `avoid_print` rule
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
